# Generated by Django 4.0.4 on 2022-05-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('importance', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('href_string', models.FileField(upload_to='docs/')),
                ('category', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('img_path', models.ImageField(upload_to='img/event/2022-05-17')),
                ('description', models.TextField()),
                ('date_publication', models.DateTimeField()),
                ('short_text', models.CharField(max_length=500)),
                ('is_slider', models.BooleanField(default=False)),
                ('imgs_path', models.CharField(max_length=255)),
                ('video', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('img_path', models.ImageField(upload_to='img/news/2022-05-17')),
                ('date_publication', models.DateTimeField()),
                ('education_departament', models.BooleanField(default=False)),
                ('is_slider', models.BooleanField(default=False)),
                ('imgs_path', models.CharField(max_length=255)),
                ('video', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='PaidServise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('cost', models.IntegerField()),
                ('imgPath', models.ImageField(upload_to='img/paidservise/')),
                ('dimensionMeasurement', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('img_path', models.ImageField(upload_to='img/park/')),
                ('park_info', models.CharField(max_length=100)),
                ('importance', models.IntegerField()),
                ('category_id', models.IntegerField()),
                ('is_slider', models.BooleanField(default=False)),
                ('img_paths', models.ImageField(default='default.jpg', upload_to='img/park/')),
            ],
        ),
        migrations.CreateModel(
            name='ParkCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(default='', max_length=250)),
                ('img_path', models.ImageField(upload_to='', verbose_name='img/park/categories/')),
            ],
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_path', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=100)),
                ('href_string', models.ImageField(upload_to='img/partners/')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('img_path', models.ImageField(upload_to='img/staff/')),
                ('href_string', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=150)),
                ('importance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('href_string', models.FileField(upload_to='video/')),
                ('date_publication', models.DateTimeField()),
            ],
        ),
    ]
