# Generated by Django 4.0.4 on 2022-05-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-date_publication', 'title']},
        ),
        migrations.AddField(
            model_name='paidservise',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='img_path',
            field=models.ImageField(upload_to='img/event/2022-05-18'),
        ),
        migrations.AlterField(
            model_name='news',
            name='img_path',
            field=models.ImageField(upload_to='img/news/2022-05-18'),
        ),
    ]
