# Generated by Django 4.0.4 on 2022-05-18 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_news_imgs_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='imgs_path',
            field=models.CharField(default='', max_length=255),
        ),
    ]
