# Generated by Django 4.0.4 on 2022-05-18 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_news_imgs_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='imgs_path',
        ),
        migrations.RemoveField(
            model_name='news',
            name='is_slider',
        ),
        migrations.AlterField(
            model_name='events',
            name='img_path',
            field=models.ImageField(upload_to='img/event/2022-05-19'),
        ),
        migrations.AlterField(
            model_name='news',
            name='img_path',
            field=models.ImageField(upload_to='img/news/2022-05-19'),
        ),
        migrations.CreateModel(
            name='NewsImgage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.news')),
            ],
        ),
    ]
