# Generated by Django 4.0.4 on 2022-05-18 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_rename_newsimgage_newsimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsimage',
            name='path',
            field=models.FileField(blank=True, default=None, upload_to='img/news/heap/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='img_path',
            field=models.ImageField(blank=True, upload_to='img/news/2022-05-19'),
        ),
        migrations.AlterField(
            model_name='newsimage',
            name='news',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='web.news'),
        ),
    ]
