# Generated by Django 4.0.4 on 2022-05-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_eventsimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=20)),
                ('path', models.CharField(default=None, max_length=255)),
                ('isActive', models.BooleanField(default=True)),
                ('importance', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='events',
            name='img_path',
            field=models.ImageField(upload_to='img/event/2022-05-21'),
        ),
        migrations.AlterField(
            model_name='eventsimage',
            name='path',
            field=models.ImageField(blank=True, default=None, upload_to='img/events/heap/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='img_path',
            field=models.ImageField(blank=True, upload_to='img/news/2022-05-21'),
        ),
        migrations.AlterField(
            model_name='newsimage',
            name='path',
            field=models.ImageField(blank=True, default=None, upload_to='img/news/heap/'),
        ),
    ]
