# Generated by Django 4.0.4 on 2022-05-22 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_navbar_alter_events_img_path_alter_eventsimage_path_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documents',
            options={'ordering': ['title', 'category']},
        ),
        migrations.AlterModelOptions(
            name='navbar',
            options={'ordering': ['importance']},
        ),
        migrations.AlterField(
            model_name='documents',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.doctype'),
        ),
        migrations.AlterField(
            model_name='events',
            name='img_path',
            field=models.ImageField(upload_to='img/event/2022-05-22'),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='importance',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='news',
            name='img_path',
            field=models.ImageField(blank=True, upload_to='img/news/2022-05-22'),
        ),
    ]
