# Generated by Django 3.2.15 on 2022-09-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_auto_20220914_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votingoption',
            name='url',
        ),
        migrations.AddField(
            model_name='votingoption',
            name='videoUrl',
            field=models.FileField(blank=True, null=True, upload_to='voteVideo', verbose_name='Загрузка видео'),
        ),
        migrations.AlterField(
            model_name='events',
            name='img_path',
            field=models.ImageField(upload_to='img/event/2022-09-26'),
        ),
        migrations.AlterField(
            model_name='news',
            name='img_path',
            field=models.ImageField(blank=True, upload_to='img/news/2022-09-26'),
        ),
    ]
