# Generated by Django 3.2.15 on 2022-09-26 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_auto_20220926_1438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='votingoption',
            old_name='videoUrl',
            new_name='url',
        ),
    ]
