# Generated by Django 3.2.12 on 2022-03-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('importance', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('href_string', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('img_path', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('date_publication', models.DateTimeField()),
                ('short_text', models.CharField(max_length=500)),
                ('is_slider', models.BooleanField(default=False)),
                ('imgs_path', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('img_path', models.ImageField(upload_to='')),
                ('date_publication', models.DateTimeField()),
                ('education_departament', models.BooleanField(default=False)),
                ('is_slider', models.BooleanField(default=False)),
                ('imgs_path', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('park_info', models.CharField(max_length=100)),
                ('importance', models.IntegerField()),
                ('category_id', models.IntegerField()),
                ('is_slider', models.BooleanField(default=False)),
                ('img_path', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ParkCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('img_path', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_path', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=100)),
                ('href_string', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('img_path', models.ImageField(upload_to='')),
                ('href_string', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=150)),
                ('importance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_path', models.ImageField(upload_to='')),
                ('href_string', models.FileField(max_length=200, upload_to='')),
                ('date_publication', models.DateTimeField()),
            ],
        ),
    ]
