# Generated by Django 4.0.3 on 2022-04-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patr_api_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='park',
            name='img_paths',
            field=models.ImageField(default='default.jpg', upload_to='img/park/'),
        ),
        migrations.AddField(
            model_name='parkcategories',
            name='url',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='documents',
            name='href_string',
            field=models.FileField(upload_to='docs/'),
        ),
        migrations.AlterField(
            model_name='events',
            name='img_path',
            field=models.ImageField(upload_to='img/event/2022-04-17'),
        ),
        migrations.AlterField(
            model_name='news',
            name='img_path',
            field=models.ImageField(upload_to='img/news/2022-04-17'),
        ),
        migrations.AlterField(
            model_name='park',
            name='img_path',
            field=models.ImageField(upload_to='img/park/'),
        ),
        migrations.AlterField(
            model_name='parkcategories',
            name='img_path',
            field=models.ImageField(upload_to='', verbose_name='img/park/categories/'),
        ),
        migrations.AlterField(
            model_name='partners',
            name='href_string',
            field=models.ImageField(upload_to='img/partners/'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='img_path',
            field=models.ImageField(upload_to='img/staff/'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='href_string',
            field=models.FileField(upload_to='video/'),
        ),
    ]
