# Generated by Django 4.0.3 on 2022-04-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patr_api_app', '0002_park_img_paths_parkcategories_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='category',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='events',
            name='img_path',
            field=models.ImageField(upload_to='img/event/2022-04-24'),
        ),
        migrations.AlterField(
            model_name='news',
            name='img_path',
            field=models.ImageField(upload_to='img/news/2022-04-24'),
        ),
    ]
