# Generated by Django 4.0.3 on 2022-04-24 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patr_api_app', '0003_alter_documents_category_alter_events_img_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='img_path',
        ),
        migrations.AddField(
            model_name='videos',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
