# Generated by Django 4.0.3 on 2022-04-24 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patr_api_app', '0004_remove_videos_img_path_videos_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaidServise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('cost', models.IntegerField()),
                ('imgPath', models.ImageField(upload_to='img/paidservise/')),
                ('dimensionMeasurement', models.CharField(max_length=50)),
            ],
        ),
    ]
