# Generated by Django 4.0.3 on 2022-04-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patr_api_app', '0006_news_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='video',
            field=models.TextField(default=''),
        ),
    ]
